name: Release

on:
  push:
    branches:
      - semantic-release   #branch name

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # commit history

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  #node version

      - name: Install dependencies
        run: npm install

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token
        run: npx semantic-release
